# Site settings
title: lilo的小站
email: luolee.me@gmail.com
description: > # 底部描述
  成功不必在我，而功力必不唐捐
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luolee.me" # the base hostname & protocol for your site
twitter_username: loyulinux
github_username:  luolee
highlighter: pygments

# Build settings
markdown: kramdown
