title: lilo在写字
email: luolee.me@gmail.com
baseurl: ""
url: "http://luolee.me"

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname:
twitter_username: loyulinux
github_username:  luolee
highlighter: pygments

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
